Repository FixMyBerlin/fixmy.frontend, pull requests merged in 2019-09, with the labels that each got.

#135 Use CONFIG_ENV to switch api urls for dev, staging, production
  config.js
  package.json
Labels: kataster-ki

#141 Commit changes from autofix
  src/App.js
  src/components/NewCloseButton.js
  src/pages/Map/components/DetailView/SectionDetail/index.js
  src/pages/Reports/ReportsState.js
  src/pages/Reports/pages/Landing/components/JoinButton.js
  src/pages/Reports/pages/OverviewMap/components/OverviewMapNavBar.js
  src/pages/Reports/pages/OverviewMap/components/ReportDetails.js
  src/pages/Reports/pages/OverviewMap/components/WebglMap.js
  src/pages/Reports/pages/SubmitReport/components/Heading.js
  src/pages/Reports/pages/SubmitReport/components/SubHeading.js
  src/pages/Reports/pages/SubmitReport/pages/AdditionalDataForm.js
  src/pages/Reports/pages/SubmitReport/pages/ReportSubmitted.js
Labels: enhancement, kataster-ki

#137 fix: empty arrays length (0) rendered in dom while clusterMarkers are…
  src/pages/Reports/pages/OverviewMap/components/WebglMap.js
Labels: bug
