Repository FixMyBerlin/fixmy.frontend, pull requests merged in 2022-03, with the labels that each got.

#975 Add page Parkraum
  src/apps/Gastro/pages/Landing/tempelberg.tsx
  src/apps/Gastro/pages/Landing/xhain.tsx
  src/apps/Spielstrassen/pages/Landing.tsx
  src/components2/Article/Quote/FaceQuote.tsx
  src/components2/Article/Quote/Quote.tsx
  src/components2/Article/Quote/index.ts
  src/components2/Article/Typography/Paragraph.tsx
  src/components2/Article/Typography/index.ts
  src/components2/Article/index.ts
  src/components2/Image/FadeInImage.tsx
  src/components2/Image/Insert.tsx
  src/components2/Image/InsertImage.tsx
  src/components2/Image/index.tsx
  src/components2/Logo/Logo.tsx
  src/components2/NewsletterWidget/NewsletterWidget.tsx
  src/components2/NewsletterWidget/index.ts
  src/components2/NewsletterWidget/index.tsx
  src/config/default/menu.ts
  src/config/default/routes.ts
  src/images/reports/felix-weisbrich-circle.jpg
  src/pages/ParkingLane/ParkingLane.test.tsx
  src/pages/ParkingLane/assets/debug-map-parking.png
  src/pages/ParkingLane/assets/felix-weisbrich-circle.jpg
  src/pages/ParkingLane/assets/map-parking-lanes.jpg
  src/pages/ParkingLane/assets/map-parking-lanes@2x.jpg
  src/pages/ParkingLane/assets/map-parking-lanes@3x.jpg
  src/pages/ParkingLane/assets/wappen.png
  src/pages/ParkingLane/assets/wappen@2x.png
  src/pages/ParkingLane/assets/wappen@3x.png
  src/pages/ParkingLane/components/NewsletterBox.tsx
  src/pages/ParkingLane/index.tsx
  src/pages/ParkingLane/sections/Section01Intro.tsx
  src/pages/ParkingLane/sections/Section02Process.tsx
  src/pages/ParkingLane/sections/Section03Participate.tsx
  src/pages/ParkingLane/sections/Section04Mapping.tsx
  src/pages/ParkingLane/sections/Section05Potential.tsx
  src/pages/ParkingLane/sections/index.ts
  src/pages/Reports/pages/Landing/berlin.tsx
  src/pages/Reports/pages/Landing/components/QuoteWeisbrich.js
  src/pages/Reports/pages/Landing/components/QuoteWeisbrich.tsx
  src/routes.tsx
Labels: enhancement

#977 Add new gastro campaign Xhain 2022
  public/uploads/offene-terrassen/Nebenbestimmungen_Schankvorgaerten.pdf
  src/apps/Gastro/components/EventPermitPark.tsx
  src/apps/Gastro/components/EventPermitParking.tsx
  src/apps/Gastro/components/GastroPermit.tsx
  src/apps/Gastro/components/HotlineNotice.tsx
  src/apps/Gastro/components/RegistrationForm/SectionCertificate.tsx
  src/apps/Gastro/components/SenderDepartment.tsx
  src/apps/Gastro/components/TrafficOrder/FeeTable.tsx
  src/apps/Gastro/components/TrafficOrder/TrafficOrderEvents.tsx
  src/apps/Gastro/components/TrafficOrder/TrafficOrderGastro.tsx
  src/apps/Gastro/components/TrafficOrder/index.ts
  src/apps/Gastro/pages/Gastro/DirectSignup.tsx
  src/apps/Gastro/pages/Landing/assets/gerold.jpg
  src/apps/Gastro/pages/Landing/assets/gerold@2x.jpg
  src/apps/Gastro/pages/Landing/assets/gerold@3x.jpg
  src/apps/Gastro/pages/Landing/assets/hermann.jpg
  src/apps/Gastro/pages/Landing/assets/hermann@2x.jpg
  src/apps/Gastro/pages/Landing/assets/hermann@3x.jpg
  src/apps/Gastro/pages/Landing/xhain.tsx
  src/apps/Gastro/types.ts
  src/config/berlin/xhain.ts
Labels: enhancement

#991 Fix netlify environment context XHain Terrassen
  src/config/berlin/xhain.ts
Labels: bug

#1005 Update dependencies
  package-lock.json
  package.json
Labels: dependencies
