Repository FixMyBerlin/fixmy.frontend, pull requests merged in 2022-01, with the labels that each got.

#924 Introduce launch.json for VSCode for debugging purposes
  .gitignore
  .vscode/launch.json
  README.md
Labels: configuration

#923 Add React Helmet & noindex meta tag to privacy/imprint markdown page
  package-lock.json
  package.json
  public/markdown/imprint.md
  public/markdown/privacy.md
  src/pages/Markdown/index.js
Labels: enhancement

#925 Remove querystring dependencies
  package-lock.json
  package.json
  src/apps/Map/MapState.ts
  src/pages/KatasterKI/pages/Landing.js
  src/pages/User/pages/Verify.js
Labels: enhancement

#935 Rename BMVI to BMDV
  public/markdown/imprint.md
  src/components2/Article/Image/Image.unit.test.tsx
  src/images/bmvi-logo.jpg
  src/images/partner/bmdv-gefoerdert.png
  src/images/partner/bmvi-gefoerdert.png
  src/images/partner/bmvi.png
  src/lang/compiled/de.json
  src/lang/compiled/en.json
  src/lang/compiled/es.json
  src/lang/translations/de.json
  src/lang/translations/en.json
  src/lang/translations/es.json
  src/pages/Research/Research.unit.test.tsx
  src/pages/Research/images/logo/BMDV_Fz_2021_Office_Farbe_de.png
  src/pages/Research/images/logo/BMVI_Fz_2017_Office_Farbe_de_clip_scale.png
  src/pages/Research/sections/07_team.tsx
Labels: enhancement

#947 Add `.editorconfig` and `.vscode` files [skip ci]
  .editorconfig
  .vscode/extensions.json
  .vscode/settings.json
Labels: configuration

#936 Improve mouse hover map
  src/apps/Map/components/WebglMap/WebglMap.tsx
  src/styles/Global.ts
Labels: enhancement

#961 Upgrade to styled-components v5
  package-lock.json
  package.json
Labels: dependencies

#964 Fix loading images from Markdown pages
  package-lock.json
  package.json
  src/pages/Markdown/components/MarkdownContent.js
Labels: bug

#955 Add search icon to search bar
  src/apps/Map/components/SearchBar.js
  src/images/search.png
Labels: enhancement

#965 Upgrade msw to 0.36.7
  package-lock.json
  package.json
Labels: dependencies

#960 Add map legend hbi
  src/apps/Map/components/Brace.js
  src/apps/Map/components/LocatorControl.js
  src/apps/Map/components/MapContent.js
  src/apps/Map/components/MapControl.js
  src/apps/Map/components/MapSelectorBar/HBILegend.js
  src/apps/Map/components/MapSelectorBar/PlanningLegend.js
  src/apps/Map/components/MapSelectorBar/SelectorBarImageWrapper.js
  src/apps/Map/components/MapSelectorBar/SelectorBarItem.js
  src/apps/Map/components/MapSelectorBar/SelectorBarWrapper.js
  src/apps/Map/components/MapSelectorBar/images/hbi-bad@2x.png
  src/apps/Map/components/MapSelectorBar/images/hbi-ok@2x.png
  src/apps/Map/components/MapSelectorBar/images/hbi-super@2x.png
  src/apps/Map/components/MapSelectorBar/images/hbi-worst@2x.png
  src/apps/Map/components/MapSelectorBar/index.js
  src/apps/Map/components/MapSwitch.js
  src/apps/Map/index.tsx
  src/components/MapLegend/CadastreLegendGrid.tsx
  src/components/MapLegend/IncidentLegendGrid.tsx
  src/components/MapLegend/Legend.tsx
  src/components/MapLegend/LegendStyles.tsx
  src/components/MapLegend/assets/close.svg
  src/components/MapLegend/assets/construction.png
  src/components/MapLegend/assets/dividers.png
  src/components/MapLegend/assets/footways.png
  src/components/MapLegend/assets/guardrail-legend.png
  src/components/MapLegend/index.ts
  src/components2/ModalCloseIcon/ModalCloseIcon.tsx
  src/components2/ModalCloseIcon/close.svg
  src/components2/ModalCloseIcon/index.ts
  src/images/location.svg
  src/images/map-legend.svg
  src/images/planung-brace.svg
  src/images/selector-brace.svg
  src/images/selector-brace_vertical.svg
  src/images/zustand-brace.svg
  src/pages/Reports/pages/OverviewMap/components/MapLegend/LegendExpanded.tsx
  src/pages/Reports/pages/OverviewMap/components/WelcomeModal/WelcomeModal.tsx
  src/pages/Reports/pages/OverviewMap/components/WelcomeModal/styles.ts
Labels: enhancement
